version: "3.9"

services:
  cadastro-clientes-api:
    build:
      context: .
      dockerfile: CadastroClientes/CadastroClientes.API/Dockerfile
    container_name: cadastro-clientes-api
    ports:
      - "5001:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CadastroClientes;Username=root;Password=root
      - RabbitMQ__HostName=rabbitmq
    networks:
      - paranabanco-net

  proposta-credito-api:
    build:
      context: .
      dockerfile: PropostaCredito/PropostaCredito.API/Dockerfile
    container_name: proposta-credito-api
    ports:
      - "5002:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=PropostaCredito;Username=root;Password=root
      - RabbitMQ__HostName=rabbitmq
    networks:
      - paranabanco-net

  cartao-credito-api:
    build:
      context: .
      dockerfile: CartaoCredito/CartaoCredito.API/Dockerfile
    container_name: cartao-credito-api
    ports:
      - "5003:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CartaoCredito;Username=root;Password=root
      - RabbitMQ__HostName=rabbitmq
    networks:
      - paranabanco-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paranabanco-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta da mensageria
      - "15672:15672"   # UI do RabbitMQ
    networks:
      - paranabanco-net

networks:
  paranabanco-net:
    driver: bridge

volumes:
  postgres_data: