version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_cadastroclientes
    environment:
      POSTGRES_USER: CadastroClienteUser
      POSTGRES_PASSWORD: CadastroClienteSenha
      POSTGRES_DB: CadastroClientes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cadastroclientes_net

  api:
    build:
      context: .
      dockerfile: CadastroClientes/CadastroClientes.API/Dockerfile
    container_name: cadastroclientes_api
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - cadastroclientes_net

volumes:
  pgdata:

networks:
  cadastroclientes_net:
    driver: bridge